baseurl      = "https://notamorningspartan.github.io"
title        = "Simplify and Automate"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Personal Blog on the current state of IT and Automation in the Enterprise landscape."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Tech blog about IT and Automation"
  keywords = "homepage, blog"
  images = [""]

  enableThemeToggle = true

  [params.author]
    name = "Tyler Kness-Miller"
  
  [params.footer]
    trademark = 2024
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Made with &#10084; by <a href='https://github.com/NotAMorningSpartan'>Tyler Kness-Miller</a>"
    ]

  [params.logo]
    logoMark = ">"
    logoText = "$ cd /home/"
    logoHomeLink = "/"
    logoCursorPathname = true
  
  [params.portrait]
    path     = "/profile.jpeg"
    alt      = "Portrait"
    maxWidth = "150px"

  [[params.social]]
    name = "github"
    url = "https://github.com/NotAMorningSpartan/"
    weight = 10
  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/knestyle"
    weight = 20
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/tkmprofile/"
    weight = 30

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
